### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by omsenjalia** [BayoDev/Twitch-Best-Of-Gen#5]
Hey, could you guide me though process of installing we driver, the docs you linked didn't work, thanks, have a good day/night

**Comment by BayoDev** [comment]
It depends on what browser you are using, remember to add the webdriver to PATH, can you give me more info such as what browser you are using and what os are you running ?

**Comment by omsenjalia** [comment]
I am using chromium chromedriver

**Comment by omsenjalia** [comment]
And ubuntu 18.04 64 bits (aarch64)

**Comment by omsenjalia** [comment]
Python 3.6.9

**Comment by BayoDev** [comment]
Selenium does not support chromium, you'll need to install chrome, tell me if it works

**Comment by omsenjalia** [comment]
Can I have instructions on installing it? I've tried installing it before using apt but didn't work, thanks

**Comment by BayoDev** [comment]
You can try <a href="https://linuxize.com/post/how-to-install-google-chrome-web-browser-on-ubuntu-20-04/">this</a>

**Comment by omsenjalia** [comment]
Alright

**Comment by BayoDev** [comment]
Did it work?

**Comment by omsenjalia** [comment]
Won't try it today cuz I have exams and I need a break

**Comment by omsenjalia** [comment]
Maybe tmr
